codecov:
  notify:
    require_ci_to_pass: true
    # wait until at all test runners have uploaded a report (see the test job's build matrix)
    # otherwise, coverage failures may be shown while some reports are still missing
    after_n_builds: 45 # must be the number of coverage report builds
comment:
  # this also configures the layout of PR check summaries / comments
  layout: "reach, diff, flags, files"
  after_n_builds: 45 # must be the number of coverage report builds
coverage:
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        # basic settings
        target: auto
        threshold: 5%
        base: auto 