name: nim-libp2p codecov builds

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        nim-options: [
          "", 
          "-d:libp2p_pubsub_anonymize=true -d:libp2p_pubsub_sign=false -d:libp2p_pubsub_verify=false", 
          "-d:libp2p_pubsub_sign=true -d:libp2p_pubsub_verify=true",
          "-d:fallback_gossipsub_10", 
          "-d:fallback_gossipsub_10 -d:libp2p_pubsub_anonymize=true -d:libp2p_pubsub_sign=false -d:libp2p_pubsub_verify=false", 
          "-d:fallback_gossipsub_10 -d:libp2p_pubsub_sign=true -d:libp2p_pubsub_verify=true"
        ]
        test-program: [
          "tests/pubsub/testpubsub",
          "tests/pubsub/testgossipinternal"
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov build-essential git curl
          mkdir coverage
          curl -O -L -s -S https://raw.githubusercontent.com/status-im/nimbus-build-system/master/scripts/build_nim.sh
          env MAKE="make -j${NPROC}" bash build_nim.sh Nim csources dist/nimble NimBinaries
          export PATH="$PATH:$PWD/Nim/bin"
          nimble install -y --depsOnly
          export NIM_OPTIONS="--lineDir:on --opt:speed -d:debug --verbosity:0 --hints:off -d:chronicles_log_level=INFO --warning[CaseTransition]:off --warning[ObservableStores]:off --warning[LockLevel]:off --nimcache:nimcache --passC:-fprofile-arcs --passC:-ftest-coverage --passL:-fprofile-arcs --passL:-ftest-coverage ${{ matrix.options }}"
          nim c $NIM_OPTIONS -r ${{ matrix.test-program }}
          lcov --capture --directory nimcache --output-file coverage/coverage.info
          lcov --extract coverage/coverage.info /mnt/e/develop/status/nim-libp2p/libp2p/* /mnt/e/develop/status/nim-libp2p/libp2p/**/* /mnt/e/develop/status/nim-libp2p/libp2p/**/**/* --output-file coverage/coverage.f.info
          genhtml coverage/coverage.f.info --output-directory coverage/output
          bash <(curl -s https://codecov.io/bash) -f coverage/coverage.f.info || echo "Codecov did not collect coverage reports"
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage/output



