name: NBC Bump PR

on:
  push:
    branches:
      - master

jobs:
  bumpNBC:
    runs-on: ubuntu-latest
    steps:
      - uses: status-im/github-app-token@v1
        name: Generate token
        id: generate-token
        with:
          app_id: ${{ secrets.BUMP_BOT_APP_ID }}
          private_key: ${{ secrets.BUMP_BOT_APP_PRIVATE_KEY }}
        
      - name: Clone NBC
        uses: actions/checkout@v2
        with:
          repository: status-im/nim-beacon-chain
          ref: devel
          path: nbc
          submodules: true
          fetch-depth: 0
      
      - name: Checkout this ref
        run: |
          cd nbc/vendor/nim-libp2p
          git checkout $GITHUB_SHA

      - name: Commit this bump
        run: |
          cd nbc
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name = "${{ github.actor }}"
          git commit -a -m "auto-bump nim-libp2p"
      
      - name: Make PR
        uses: status-im/create-pull-request@v3
        with:
          branch: nim-libp2p-auto-bump
          path: nbc
          token: ${{ steps.generate-token.outputs.token }}
          title: nim-libp2p auto bump


